/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as CapitalRouteImport } from './routes/capital'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as DataRouteImport } from './routes/data'
import { Route as EquitiesRouteImport } from './routes/equities'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalRoute = CapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const EquitiesRoute = EquitiesRouteImport.update({
  id: '/equities',
  path: '/equities',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/businesses': typeof BusinessesRoute
  '/capital': typeof CapitalRoute
  '/charts': typeof ChartsRoute
  '/data': typeof DataRoute
  '/equities': typeof EquitiesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/businesses': typeof BusinessesRoute
  '/capital': typeof CapitalRoute
  '/charts': typeof ChartsRoute
  '/data': typeof DataRoute
  '/equities': typeof EquitiesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/businesses': typeof BusinessesRoute
  '/capital': typeof CapitalRoute
  '/charts': typeof ChartsRoute
  '/data': typeof DataRoute
  '/equities': typeof EquitiesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/businesses'
    | '/capital'
    | '/charts'
    | '/data'
    | '/equities'
    | '/legal'
    | '/login'
    | '/methodology'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/businesses'
    | '/capital'
    | '/charts'
    | '/data'
    | '/equities'
    | '/legal'
    | '/login'
    | '/methodology'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/businesses'
    | '/capital'
    | '/charts'
    | '/data'
    | '/equities'
    | '/legal'
    | '/login'
    | '/methodology'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessesRoute: typeof BusinessesRoute
  CapitalRoute: typeof CapitalRoute
  ChartsRoute: typeof ChartsRoute
  DataRoute: typeof DataRoute
  EquitiesRoute: typeof EquitiesRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital': {
      id: '/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof CapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equities': {
      id: '/equities'
      path: '/equities'
      fullPath: '/equities'
      preLoaderRoute: typeof EquitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessesRoute: BusinessesRoute,
  CapitalRoute: CapitalRoute,
  ChartsRoute: ChartsRoute,
  DataRoute: DataRoute,
  EquitiesRoute: EquitiesRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
